### ISSUE TITLE
Module build failed: TypeError: ngAnnotate is not a function

### ISSUE THREAD

**Issue by huguangju** [anlambert/webpack-gulp-es6-angular-express#5]
Run with `npm run start` or other, report error:

```
... ...
ERROR in ./src/website/bootstrapApp.js
Module build failed: TypeError: ngAnnotate is not a function
    at Object.module.exports (/Users/hugo/programming/github/workflow/webpack-gulp-es6-angular-express/node_modules/ng-annotate-loader/loader.js:68:24)

... ...

ERROR in ./src/server/main.js
Module build failed: TypeError: ngAnnotate is not a function
    at Object.module.exports (/Users/hugo/programming/github/workflow/webpack-gulp-es6-angular-express/node_modules/ng-annotate-loader/loader.js:68:24)
 @ multi main
```

**Comment by anlambert** [comment]
I assume you are working on Windows ... I have just updated the repository, that issue should now be fixed.

**Comment by huguangju** [comment]
As shown absolute path above, i am not working on Win.

My env is:
 `OS: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"`
`Node:  v5.0.0`
`Webpack: 1.13.1`

And this error still exists.

**Comment by anlambert** [comment]
Delete the 'node_modules/ng-annotate-loader' folder at the root of the project, do 'npm install' and it should work

**Comment by huguangju** [comment]
Thank you very much. it works now.
